#define PPICLF_LRS 4
#define PPICLF_LRP 6
#define PPICLF_LEE 1000
#define PPICLF_LEX 6
#define PPICLF_LEY 6
#define PPICLF_LRP_INT 3
#define PPICLF_LRP_PRO 3

#define PPICLF_JX 1
#define PPICLF_JY 2
#define PPICLF_JVX 3
#define PPICLF_JVY 4
#define PPICLF_R_JRHOP 1
#define PPICLF_R_JDP 2
#define PPICLF_R_JVOLP 3
#define PPICLF_R_JPHIP 4
#define PPICLF_R_JUX 5
#define PPICLF_R_JUY 6
#define PPICLF_P_JPHIP 1
#define PPICLF_P_JFX 2
#define PPICLF_P_JFY 3
