#include "PPICLF_USER.h"
#include "PPICLF_STD.h"
C Wall support
      REAL*8 PPICLF_WALL_C(9,PPICLF_LWALL),PPICLF_WALL_N(4,PPICLF_LWALL)
      COMMON /PPICLF_WALL_R/ PPICLF_WALL_C,PPICLF_WALL_N

      INTEGER*4  PPICLF_NWALL
      COMMON /PPICLF_WALL_N/ PPICLF_NWALL

C Mirror wall particles
      REAL*8 PPICLF_XYZ_MIRROR(3,PPICLF_LWALL)
      COMMON /PPICLF_WALL_MIRROR_R/ PPICLF_XYZ_MIRROR

      INTEGER*4 PPICLF_NWALL_M
      COMMON /PPICLF_WALL_MIRROR_N/ PPICLF_NWALL_M
