#include "PPICLF_USER.h"
#include "PPICLF_STD.h"
C Grid
      REAL*8  PPICLF_XDRANGE(2,3), PPICLF_XERANGE(2,3,PPICLF_LEE)
      COMMON /PPICLF_GRID_RANGE_R/ PPICLF_XDRANGE, PPICLF_XERANGE

      COMMON /PPICLF_GRID_FLD_R/ PPICLF_PRO_FLD, PPICLF_INT_FLD
     >                          ,PPICLF_INT_FLDU ,PPICLF_PRO_FLDB 
     >                          ,PPICLF_XM1B ,PPICLF_XM1BS, PPICLF_XM1BI
      REAL*8 PPICLF_PRO_FLD (PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ,PPICLF_LEE
     >                      ,PPICLF_LRP_PRO),
     >       PPICLF_INT_FLDU(PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ
     >                      ,PPICLF_LEE,PPICLF_LRP_INT),
     >       PPICLF_INT_FLD (PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ
     >                      ,PPICLF_LRP_INT,PPICLF_LEE),
     >       PPICLF_PRO_FLDB(PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ
     >                      ,PPICLF_LRP_PRO,PPICLF_LEE),
     >       PPICLF_XM1B    (PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ,3
     >                      ,PPICLF_LEE),
     >       PPICLF_XM1BS   (PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ
     >                      ,3,PPICLF_LEE),
     >       PPICLF_XM1BI   (PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ
     >                      ,PPICLF_LEE,3)

      COMMON /PPICLF_GRID_BIN_MAP_I/ PPICLF_ER_MAP,PPICLF_ER_MAPC
     >                        ,PPICLF_ER_MAPS,PPICLF_EL_MAP
     >                        ,PPICLF_MODGP,PPICLF_NELTB,PPICLF_NELTBB
     >                        ,PPICLF_NELTBBB
      INTEGER*4 PPICLF_ER_MAP (PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_ER_MAPC(PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_ER_MAPS(PPICLF_LRMAX,PPICLF_LEE),
     >         PPICLF_MODGP  (PPICLF_LEX,PPICLF_LEY,PPICLF_LEZ
     >                       ,PPICLF_LEE,4),
     >         PPICLF_EL_MAP (8,PPICLF_LEE), PPICLF_NELTB,PPICLF_NELTBB,
     >         PPICLF_NELTBBB

      INTEGER*4 PPICLF_NEE
      COMMON /PPICLF_GRID_ORIG_CELL_N/ PPICLF_NEE

      INTEGER*4 PPICLF_INT_ICNT, PPICLF_INT_MAP(PPICLF_LRP_INT)
      COMMON /PPICLF_INTERP_I/ PPICLF_INT_ICNT, PPICLF_INT_MAP

